#!/usr/bin/env bash
# Fetch secrets from Google Secret Manager into .env (inverse of update-secrets.sh).
#
# Prerequisites:
#   gcloud auth login
#   gcloud config set project finto-477904
#   roles/secretmanager.secretAccessor on secrets you need
#
# Usage:
#   ./fetch-secrets.sh              # all secrets in the GCP project
#   ./fetch-secrets.sh --known-only # only the SECRETS list (same as update-secrets.sh)
#   ENV_FILE=.env.local ./fetch-secrets.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

PROJECT_ID="${GCP_PROJECT_ID:-finto-477904}"
ENV_FILE="${ENV_FILE:-.env}"
KNOWN_ONLY=false

# Same keys as finto/.env / cloudbuild.yaml (app runtime secrets). Ground truth: .env
KNOWN_SECRETS=(
  "ANTHROPIC_API_KEY"
  "DATABASE_URL"
  "GOOGLE_API_KEY"
  "GOOGLE_CLIENT_ID"
  "HF_TOKEN"
  "LANGSMITH_API_KEY"
  "LANGSMITH_ENDPOINT"
  "LANGSMITH_PROJECT"
  "LANGSMITH_TRACING"
  "NEWS_MODEL"
  "OPENAI_API_KEY"
  "PINECONE_API_KEY"
  "PORTFOLIO_MODEL"
  "ROUTER_MODEL"
  "SECRET_KEY"
  "SENDGRID_API_KEY"
  "SENDGRID_FROM_EMAIL"
  "SENDGRID_FROM_NAME"
  "TAVILY_API_KEY"
  "TIMESCALE_DATABASE_URL"
  "THESYS_API_KEY"
  "THESYS_BASE_URL"
  "THESYS_ENABLED"
  "THESYS_MODEL"
  "WA_APP_SECRET"
  "WA_PHONE_NUMBER_ID"
  "WA_SENDER_E164"
  "WA_USER_OR_SYSTEM_TOKEN"
  "WA_VERIFY_TOKEN"
  "ALPACA_API_KEY"
  "ALPACA_API_SECRET"
  "ALPACA_STREAM_URL"
  "DEMO_US_STOCK_SIMULATE"
  "DEMO_US_STOCK_SIMULATE_TICK_SECONDS"
)

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Fetch secret values from Google Secret Manager and write them to $ENV_FILE.

Options:
  --known-only   Fetch only the known app secrets (update-secrets.sh list)
  -h, --help     Show this help

Environment:
  GCP_PROJECT_ID   GCP project (default: finto-477904)
  ENV_FILE         Output file (default: .env)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --known-only)
      KNOWN_ONLY=true
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if ! command -v gcloud &>/dev/null; then
  echo "Error: gcloud CLI not found. Install: https://cloud.google.com/sdk/docs/install" >&2
  exit 1
fi

if ! gcloud auth print-access-token --project="$PROJECT_ID" &>/dev/null; then
  echo "Error: gcloud is not authenticated. Run: gcloud auth login" >&2
  exit 1
fi

escape_env_value() {
  local value="$1"
  if [[ "$value" =~ ^[A-Za-z0-9_./:@+-]+$ ]]; then
    printf '%s' "$value"
  else
    local escaped="${value//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    escaped="${escaped//$'\n'/\\n}"
    escaped="${escaped//$'\r'/\\r}"
    printf '"%s"' "$escaped"
  fi
}

fetch_secret() {
  local secret_name="$1"
  gcloud secrets versions access latest \
    --secret="$secret_name" \
    --project="$PROJECT_ID" 2>/dev/null
}

if [[ -f "$ENV_FILE" ]] && [[ -s "$ENV_FILE" ]]; then
  backup="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$backup"
  echo "Backed up existing $ENV_FILE to $backup"
fi

secret_names=()
if [[ "$KNOWN_ONLY" == true ]]; then
  secret_names=("${KNOWN_SECRETS[@]}")
else
  echo "Listing secrets in project $PROJECT_ID..."
  while IFS= read -r name; do
    [[ -n "$name" ]] && secret_names+=("$name")
  done < <(gcloud secrets list --project="$PROJECT_ID" --format='value(name)' | sort)
fi

if ((${#secret_names[@]} == 0)); then
  echo "No secrets found." >&2
  exit 1
fi

{
  echo "# Generated by fetch-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "# Project: $PROJECT_ID"
  echo
} >"$ENV_FILE"

fetched=0
skipped=0
failed=0

for secret_name in "${secret_names[@]}"; do
  [[ -z "$secret_name" ]] && continue

  if ! gcloud secrets describe "$secret_name" --project="$PROJECT_ID" &>/dev/null; then
    echo "Warning: secret $secret_name not found, skipping..." >&2
    ((skipped++)) || true
    continue
  fi

  if ! secret_value="$(fetch_secret "$secret_name")"; then
    echo "Warning: could not read $secret_name (check secretAccessor), skipping..." >&2
    ((failed++)) || true
    continue
  fi

  # gcloud may append a trailing newline; keep intentional internal newlines.
  secret_value="${secret_value%$'\n'}"

  printf '%s=%s\n' "$secret_name" "$(escape_env_value "$secret_value")" >>"$ENV_FILE"
  echo "Fetched $secret_name"
  ((fetched++)) || true
done

echo
echo "Wrote $fetched secret(s) to $ENV_FILE (skipped: $skipped, failed: $failed)"

if ((failed > 0)); then
  exit 1
fi
