"""add equity_holdings_in table

Revision ID: 00feae39281d
Revises: c30d1e5afb86
Create Date: 2025-11-11 18:36:39.035117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00feae39281d'
down_revision: Union[str, None] = 'c30d1e5afb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_holdings_in',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('isin', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('qty_available', sa.Integer(), nullable=False),
    sa.Column('qty_discrepant', sa.Integer(), nullable=False),
    sa.Column('qty_long_term', sa.Integer(), nullable=False),
    sa.Column('qty_pledged_margin', sa.Integer(), nullable=False),
    sa.Column('qty_pledged_loan', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('prev_close_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unrealized_pnl_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['f_users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.broker_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equity_holdings_in')
    # ### end Alembic commands ###

