"""baseline from sqlalchemy models

Revision ID: 6ea001377ab4
Revises:
Create Date: 2025-11-11 11:20:53.415012

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ea001377ab4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed op.drop_table('alembic_version') - this is Alembic's version tracking table
    op.alter_column(
        "f_users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "f_users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("f_users_email_key"), "f_users", type_="unique")
    op.drop_constraint(op.f("f_users_username_key"), "f_users", type_="unique")
    op.drop_index(op.f("idx_f_users_email"), table_name="f_users")
    op.drop_index(op.f("idx_f_users_username"), table_name="f_users")
    op.create_index(op.f("ix_f_users_email"), "f_users", ["email"], unique=True)
    op.create_index(op.f("ix_f_users_username"), "f_users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_f_users_username"), table_name="f_users")
    op.drop_index(op.f("ix_f_users_email"), table_name="f_users")
    op.create_index(op.f("idx_f_users_username"), "f_users", ["username"], unique=False)
    op.create_index(op.f("idx_f_users_email"), "f_users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("f_users_username_key"), "f_users", ["username"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("f_users_email_key"), "f_users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "f_users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "f_users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # Note: Removed op.create_table('alembic_version') - don't recreate Alembic's version tracking table
    # ### end Alembic commands ###
