"""Pydantic schemas for the Daily Stock Game API."""

from __future__ import annotations

from datetime import date
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field, field_validator

# ── Requests ────────────────────────────────────────────────────────────────


class StockSearchResult(BaseModel):
    """A single stock match returned by the autocomplete search."""

    symbol: str
    symbol_ns: str
    company_name: str


class StockSearchResponse(BaseModel):
    """Response for GET /game/stocks/search."""

    query: str
    results: list[StockSearchResult]
    semantic: bool = False  # True when results came from Pinecone semantic search


class SubmitPicksRequest(BaseModel):
    """User submits 5 stock symbols for today's contest."""

    stocks: list[str] = Field(
        ..., min_length=5, max_length=5, description="Exactly 5 stock symbols"
    )

    @field_validator("stocks")
    @classmethod
    def validate_stocks(cls, v: list[str]) -> list[str]:
        cleaned = [s.strip().upper() for s in v]
        if len(set(cleaned)) != 5:
            raise ValueError("All 5 stocks must be unique")
        if any(len(s) == 0 for s in cleaned):
            raise ValueError("Stock symbol cannot be empty")
        return cleaned


class AnonSubmitPicksRequest(BaseModel):
    """Anonymous user submits 5 stock symbols."""

    anon_id: str = Field(
        ...,
        min_length=8,
        max_length=64,
        description="Client-generated UUID stored in localStorage — acts as anonymous identity",
    )
    display_name: str = Field(
        ...,
        min_length=2,
        max_length=30,
        description="Name shown on leaderboard (generated by client, user can edit)",
    )
    stocks: list[str] = Field(..., min_length=5, max_length=5)

    @field_validator("stocks")
    @classmethod
    def validate_stocks(cls, v: list[str]) -> list[str]:
        cleaned = [s.strip().upper() for s in v]
        if len(set(cleaned)) != 5:
            raise ValueError("All 5 stocks must be unique")
        if any(len(s) == 0 for s in cleaned):
            raise ValueError("Stock symbol cannot be empty")
        return cleaned

    @field_validator("display_name")
    @classmethod
    def sanitize_name(cls, v: str) -> str:
        import re

        # strip anything that isn't alphanumeric, space, dash, underscore
        cleaned = re.sub(r"[^\w\s\-]", "", v).strip()
        if not cleaned:
            raise ValueError("Display name contains no valid characters")
        return cleaned


class AnonPickConfirmation(BaseModel):
    """Returned after an anonymous user successfully submits picks."""

    pick_id: UUID
    contest_date: date
    anon_id: str
    display_name: str
    stocks: list[str]
    message: str = "Picks locked! Check the leaderboard after market close."


# ── Responses ───────────────────────────────────────────────────────────────


class PickConfirmation(BaseModel):
    """Returned after successfully submitting picks."""

    pick_id: UUID
    contest_date: date
    stocks: list[str]
    message: str = "Picks locked! Check the leaderboard after market close."


class StockBreakdown(BaseModel):
    """Per-stock return in the result."""

    symbol: str
    return_pct: Optional[float] = None


class MyResultResponse(BaseModel):
    """User's own result for a given contest day."""

    contest_date: date
    stocks: list[StockBreakdown]
    portfolio_return_pct: Optional[float] = None
    nifty_return_pct: Optional[float] = None
    excess_return_pct: Optional[float] = None
    rank: Optional[int] = None
    total_participants: int
    is_settled: bool


class LeaderboardEntry(BaseModel):
    """Single row in the leaderboard."""

    rank: int
    user_id: Optional[UUID] = None
    display_name: str
    is_anonymous: bool
    stocks: list[str]
    portfolio_return_pct: float
    excess_return_pct: float


class LiveStockPerformance(BaseModel):
    """Real-time per-stock data for the polling endpoint."""

    symbol: str
    entry_price: Optional[float] = None
    current_price: Optional[float] = None
    return_pct: Optional[float] = None


class VibeBlock(BaseModel):
    """Fun battle-tier summary computed by the backend — render directly in UI.

    tier:    machine-readable key for conditional styling
    emoji:   display emoji
    label:   short punchy title  e.g. "On Fire"
    message: one-liner flavour text
    vs_bar:  float -100..+100, use as CSS translateX / width offset for tug-of-war bar
    color:   tailwind color hint: 'emerald' | 'green' | 'yellow' | 'orange' | 'red' | 'gray'
    """

    tier: str
    emoji: str
    label: str
    message: str
    vs_bar: float
    color: str


class LivePerformanceResponse(BaseModel):
    """Returned by GET /game/live-performance — polled every 5s by the UI."""

    contest_date: date
    is_settled: bool
    stocks: list[LiveStockPerformance]
    portfolio_return_pct: Optional[float] = None
    nifty_return_pct: Optional[float] = None
    nifty_current_price: Optional[float] = None
    excess_return_pct: Optional[float] = None
    vibe: VibeBlock
    refreshed_at: str


class LeaderboardResponse(BaseModel):
    """Full leaderboard for a contest day."""

    contest_date: date
    nifty_return_pct: Optional[float] = None
    is_settled: bool
    total_participants: int
    leaderboard: list[LeaderboardEntry]


class ContestStatusResponse(BaseModel):
    """Quick status check: has the user already submitted today?"""

    contest_date: date
    active_contest_date: date
    has_submitted: bool
    is_settled: bool
    phase: str  # 'open' | 'submitted' | 'settled'
    total_participants: int


class HistoryStockBreakdown(BaseModel):
    """Per-stock detail in a historical pick entry."""

    symbol: str
    entry_price: Optional[float] = None
    return_pct: Optional[float] = None


class PickHistoryEntry(BaseModel):
    """A single day's pick entry in the user's history."""

    contest_date: date
    is_settled: bool
    stocks: list[HistoryStockBreakdown]
    portfolio_return_pct: Optional[float] = None
    nifty_return_pct: Optional[float] = None
    excess_return_pct: Optional[float] = None
    rank: Optional[int] = None


class PicksHistoryResponse(BaseModel):
    """Response for GET /game/my-history."""

    history: list[PickHistoryEntry]


class ProfileHistoryEntry(BaseModel):
    """A single day's entry in a public player profile."""

    contest_date: date
    is_settled: bool
    stocks: list[str]
    portfolio_return_pct: Optional[float] = None
    nifty_return_pct: Optional[float] = None
    excess_return_pct: Optional[float] = None
    rank: Optional[int] = None
    total_participants: Optional[int] = None


class PlayerProfileResponse(BaseModel):
    """Public player profile — no private fields exposed."""

    user_id: str
    username: str
    full_name: Optional[str] = None
    total_games: int
    wins: int
    history: list[ProfileHistoryEntry]
